ladybug-tools/honeybee

honeybee/radiance/command/gendaymtx.py, honeybee/radiance/datatype.py
A minor path based correction to the file path descriptor.
Added a path to test for wea file in gendaymtx.
=> Patched file path descriptor, path test for wea in gendaymtx 

honeybee/radiance/command/gendaymtx.py, honeybee/radiance/command/gensky.py, honeybee/radiance/command/rcollate.py, honeybee/radiance/datatype.py, test.py
Implemented documentation for gendaymtx through the use of descriptors.
Fixed some attribute naming issues.
Add docstrings for all descriptors.
=> Implemented some prototypical docstrings through descriptors.

honeybee/radiance/command/rfluxmtx.py, honeybee/radiance/command/rtrace.py, honeybee/radiance/parameters/_defaultset.py, honeybee/radiance/parameters/imagebased.py, honeybee/radiance/recipe/annual.py, honeybee/radiance/recipe/sunlighthours.py, scripts/ThreePhaseIllum.py, scripts/ThreePhaseImage.py, scripts/TwoPhaseIllum.py, scripts/TwoPhaseImage.py
1. Also made a correction to the Two Phase Image script. Still needs work as there appears to be no Radiance-native to combine all images together in the case of separate HDRs for sky and ground.
=> Updated scripts to create temp folder if required.

honeybee/radiance/command/rpict.py, honeybee/radiance/parameters/_defaultset.py, honeybee/radiance/parameters/imagebased.py
1. Implemented rpict.
2. Couple of big fixed to image based parameters and defaultset.py
=> Rpict, couple of bug fixes.

honeybee/radiance/command/_commandbase.py, honeybee/radiance/command/genBSDF.py, honeybee/radiance/parameters/genBsdf.py, tests/radiance_command_genBSDF_test.py
1. Full code implementation of GenBSDF sans some class methods for translating geometry.
=> GenBSDF (beta):

honeybee/config.py, honeybee/radiance/command/genBSDF.py, honeybee/radiance/command/raBmp.py, honeybee/radiance/command/raTiff.py, honeybee/radiance/command/xform.py, honeybee/radiance/parameters/raBmp.py, honeybee/radiance/parameters/raTiff.py, tests/radiance_command_genBSDF_test.py, tests/radiance_command_raBmp_test.py, tests/radiance_command_raTiff_test.py
1. Rabmp and ratiff have been tested.
2. genBSDF is still WIP.
=> RaBmp,RaTiff,genBSDF

honeybee/radiance/command/pcomb.py, honeybee/radiance/command/rmtxop.py, scripts/improvedDC.py
@mostaphaRoudsari , this turned out to be trickier than I expected! I have added complex matrices to rmtxop and added some [docstrings](https://github.com/sariths/honeybee/blob/master/honeybee/radiance/command/rmtxop.py#L62-L90) on how to use this. I moved some stuff around to ensure that scripts [like this one ](https://github.com/sariths/honeybee/blob/master/honeybee/radiance/recipe/threephase/gridbased.py) (still relevant?) are not broken.
Anyway, things look cleaner now: [Before](https://github.com/ladybug-tools/honeybee/blob/master/scripts/improvedDC.py#L177-L194) and [after](https://github.com/sariths/honeybee/blob/master/scripts/improvedDC.py#L180-L201).
Here is a quick check to prove that from a results perspective, everything is still the same..(check the last line). 
Python …
=> Full Rmtxop, Pcomb bug

honeybee/radiance/analysisgrid.py, honeybee/radiance/analysispoint.py, honeybee/radiance/recipe/daylightcoeff/gridbased.py, honeybee/radiance/recipe/parameters.py, honeybee/radiance/recipe/recipedcutil.py, honeybee/radiance/recipe/threephase/gridbased.py, honeybee/schedule.py
Added a number of new method to `AnalysisGrid`, `AnalysisPoint` and `Schedule` to finish post-processing components. I tested them by creating the components in Grasshopper but the results needs to be double checked.
=> Finished postprocessing methods

honeybee/hbfensurface.py, honeybee/hbsurface.py, honeybee/radiance/analysispoint.py, honeybee/radiance/recipe/threephase/gridbased.py
=> Surface.fromGeometry accepts list of names

honeybee/_hbanalysissurface.py, honeybee/radiance/analysisgrid.py, honeybee/radiance/material/glass.py, honeybee/radiance/material/glow.py, honeybee/radiance/material/metal.py, honeybee/radiance/material/plastic.py, honeybee/radiance/parameters/_parametersbase.py, honeybee/radiance/parameters/gridbased.py, honeybee/radiance/recipe/annual/gridbased.py, honeybee/radiance/recipe/daylightcoeff/gridbased.py, honeybee/radiance/recipe/daylightfactor/gridbased.py, honeybee/radiance/recipe/fivephase/gridbased.py, honeybee/radiance/recipe/pointintime/gridbased.py, honeybee/radiance/recipe/radiation/gridbased.py, honeybee/radiance/recipe/solaraccess/gridbased.py, honeybee/radiance/recipe/threephase/gridbased.py, honeybee/radiance/sky/certainIlluminance.py, honeybee/radiance/sky/skymatrix.py
Proposing the following implementations of to and from json for most/all gridbased recipes. I have run the tests in jupyter notebook and am currently testing in grasshopper with the objective of also testing sending json recipe to a server running honeybee docker image. Happy for @mostaphaRoudsari or @sariths to review so I can keep building more here before committing to master. ps; this is fun, thanks for letting me get in on this!
PS: I'm 90% sure there are going to be some issues with Pep8! I'd still like a code review before investing time in pep8 clean up (so I can make sure I'm on the right road at least)
=> implemented from and to json for most recipes

honeybee/radiance/material/materialbase.py, honeybee/radiance/primitive.py, honeybee/radiance/properties.py, honeybee/radiance/scene.py, tests/dev_tests/materials_test.py
Fixed the issue with sub-classing primitives.
Updated Scene structure.
=> Improved Scene and Primitive classes

honeybee/radiance/analysisgrid.py, honeybee/radiance/analysispoint.py, honeybee/radiance/imagecollection.py, honeybee/radiance/recipe/annual/gridbased.py, honeybee/radiance/recipe/daylightcoeff/gridbased.py, honeybee/radiance/recipe/daylightfactor/gridbased.py, honeybee/radiance/recipe/directreflection/gridbased.py, honeybee/radiance/recipe/fivephase/gridbased.py, honeybee/radiance/recipe/pointintime/gridbased.py, honeybee/radiance/recipe/radiation/gridbased.py, honeybee/radiance/recipe/recipedcutil.py, honeybee/radiance/recipe/recipexphaseutil.py, honeybee/radiance/recipe/solaraccess/gridbased.py, honeybee/radiance/recipe/threephase/gridbased.py, honeybee/radiance/sky/sunmatrix.py
This commit adds support for timesteps shorter than 1. It was a required change to load the results for radiation and sunlight hours study for every 10 minutes.
=> Timestep support

honeybee/radiance/material/trans.py, tests/radiance_material_trans_test.py
Also fixed the bug with classmethod found by Peter. I couldn't find his handle on GitHub to add him here
=> Added test for Radiance trans material

honeybee/radiance/resultcollection/imagecollection.py
See https://github.com/ladybug-tools/honeybee-grasshopper/pull/25#issuecomment-434121583
=> Fixed issue with importing pcomb library

MANIFEST.in, setup.py
config.json was missing from the package. It should be add to the package noe. See https://python-packaging.readthedocs.io/en/latest/non-code-files.html
=> fix(*): add config.json to package

honeybee/radiance/analysisgrid.py
See: https://discourse.ladybug.tools/t/how-to-load-the-results-from-a-file-into-grasshopper-using-honeybee-api/3437/26
=> fix(analysis grid): fix IronPython overload issue

.travis.yml, setup.cfg
Check out the Travis job to see the difference.
=> ci(travis): split test and deploy jobs

honeybee/dataoperation.py, honeybee/futil.py, honeybee/radiance/analysisgrid.py, honeybee/radiance/command/_commandbase.py, honeybee/radiance/command/getinfo.py, honeybee/radiance/datatype.py, honeybee/radiance/material/bsdf.py, honeybee/radiance/parameters/_parametersbase.py, honeybee/radiance/resultcollection/database.py, honeybee/radiance/sky/analemma.py, honeybee/radiance/sky/gendaylit.py
In Python3 map returns a map object and not a list. map doesn't have a length and this casues an
issue in data validation. This is now fixed.
=> fix(datatype): change map to list to fix issue in py3

honeybee/radiance/analysisgrid.py, honeybee/radiance/analysispoint.py, honeybee/radiance/datatype.py, honeybee/radiance/recipe/_gridbasedbase.py, honeybee/radiance/recipe/daylightfactor/gridbased.py, honeybee/radiance/recipe/id.py, honeybee/radiance/recipe/solaraccess/gridbased.py, honeybee/radiance/sky/skymatrix.py
I started addressing a number of issues posted on the forum for honeybee-grasshopper plugin and some of them rooted into honeybee and recent changes in ladybug libraries. I fixed those.
Also fixed two bugs found by Theodore.
Since these are small changes and will be replaced soon anyways with `honeybee-radiance` I'm going to merge this in so I can fix `honeybee-grasshopper` and push the fixes to that repository.
=> A number of small fixes

README.md, honeybee/radiance/command/_commandbase.py, honeybee/radiance/recipe/_recipebase.py
Added permission change for executable files. I'm not sure how our tests never failed on this.
resolves: #291
=> fix(recipebase): fix executable permission

honeybee/radiance/sky/_pointintimesky.py, honeybee/radiance/sky/climatebased.py, honeybee/radiance/sky/skymatrix.py, requirements.txt, tests/radiance_recipe_solaraccess_test.py, tests/radiance_sky_sunmtx_test.py
Changed hasattr check to isinstance to be compatible with ladybug 0.19.0
=> fix(skymtx): update wea type check

.travis.yml, deploy.sh, honeybee_plus/radiance/sky/skymatrix.py
The wea class has changed and write doesn't accept the hourly filtering anymore. The filtering should be done in a separate step.
=> fix(skymatrix): update write to wea
